name: Delete test

on:
  workflow_dispatch:
    inputs:
      majorVersion:
        description: 'App version'
        required: true

jobs:
  test:
    runs-on: [ubuntu-latest]
    steps:
      - name: Subtract
        run: echo "DELETE_VERSION=$((${{ github.event.inputs.majorVersion }}-2))" >> $GITHUB_ENV
      - name: Delete
        if: ${{ env.DELETE_VERSION > 0 }}
        run: |
          echo ${{ env.DELETE_VERSION }}

